### ISSUE TITLE
10V ref suggestion

### ISSUE THREAD

**Issue by raspberry007** [uChip/VoltageReferenceProgrammable#2]
Hello,

Thanks for an excellent project first of all and apologies for writing into "issues" section.
I wonder if it is possible to modify your reference to be able to have voltage from 0 to 10V. 
I think it would be a much more useful range. What would you suggest to modify? 
I'll probably use ref102 10V Vref or a more precise 10V LM399.

Another improvement could be using a TFT 3.5" display to set voltage output rather than using a potentiometer. I have already made some progress on this.

Thank you.
Alex

**Comment by uChip** [comment]
Every design is a collection of engineering trade offs.  You can certainly do a 10V reference.  In fact there are several designs already published.  One of my favorites is the one done by Ian Johnston https://www.youtube.com/watch?v=f4E10GpvfZs  Since most of my work is with low voltage devices (Arduino, Raspberry Pi) the 5V range fit my needs better.  But feel free to fork my design and change or elaborate as you like.
Thanks for your kind words and have fun with your project!
  - Chip

**Comment by raspberry007** [comment]
Yes, I have been following Ian since he started constructing his Vref. I even had a chat with him recently about it on the eevblog. My idea however is slightly different. I do want to build a vref with a touch display driven by atmega2560 or similar IC. I have the interface reading though I am sure it is going to evolve. Now I am testing different vref IC. I really liked ref102. Alternatively, I may use just like Ian LM399. I have one currently being aged. 

Thanks
Alex
